
-----table login
CREATE TABLE CDT.CDT_LOGIN
(	USERID VARCHAR2(50) NOT NULL, 
	USERTEN VARCHAR2(100) NOT NULL,   
	USERPASS VARCHAR2(50) NOT NULL,
  USERTYPE number(1,0) NOT NULL,
  CONSTRAINT DT_USERID_PK PRIMARY KEY (USERID)
);

INSERT INTO CDT.CDT_LOGIN SELECT * FROM HSOFTDKBD.DT_LOGIN
select * from CDT.CDT_LOGIN
------ table Benh vien
CREATE TABLE CDT.CDT_BENHVIEN
(	DONVIID NUMBER(2,0) NOT NULL , 
	DONVITEN NVARCHAR2(100) NOT NULL, 
	DONVIVIETTAT NVARCHAR2(30), 
  CONSTRAINT DT_DONVI_PK PRIMARY KEY (DONVIID)
);

INSERT INTO CDT.CDT_BENHVIEN select * from HSOFTDKBD.DT_BENHVIEN
select * from HSOFTDKBD.DT_LOGIN where userid = '1' and userpass = '1';
DROP TABLE HSOFTDKBD.DT_LOAICHUNGNHAN
delete HSOFTDKBD.DT_LOAICHUNGNHAN
--------table chung nhan dao tao

CREATE TABLE hsoftdkbd.DT_CNDAOTAO  
( CNDTID number(3) NOT NULL,  
  CNDTTEN varchar2(100) NOT NULL,  
  CONSTRAINT CNDTID_PK PRIMARY KEY (CNDTID)  
);

CREATE TABLE hsoftdkbd.DT_DMLOAICHUNGNHAN  
( DMLOAICHUNGNHANID number(3) NOT NULL,  
  DMLOAICHUNGNHANTEN varchar2(100) NOT NULL,  
  CONSTRAINT DMLOAICHUNGNHANID_PK PRIMARY KEY (DMLOAICHUNGNHANID)  
);

select * from hsoftdkbd.DT_DMLOAICHUNGNHAN 

select * from hsoftdkbd.DT_DMLOAICHUNGNHAN  
INSERT INTO HSOFTDKBD.DT_DMLOAICHUNGNHAN (DMLOAICHUNGNHANID, DMLOAICHUNGNHANTEN) VALUES (1,'C?p ch?ng ch?');
INSERT INTO HSOFTDKBD.DT_DMLOAICHUNGNHAN (DMLOAICHUNGNHANID, DMLOAICHUNGNHANTEN) VALUES (2,'C?p ch?ng nh?n');
INSERT INTO HSOFTDKBD.DT_DMLOAICHUNGNHAN (DMLOAICHUNGNHANID, DMLOAICHUNGNHANTEN) VALUES (3,'C?p xác nh?n');
INSERT INTO HSOFTDKBD.DT_DMLOAICHUNGNHAN (DMLOAICHUNGNHANID, DMLOAICHUNGNHANTEN) VALUES (4,'Không c?p gi?y');


SELECT * FROM  HSOFTDKBD.DT_CHUCDANH

SELECT * FROM HSOFTDKBD.DT_BENHVIEN

------ table Khoa phong
CREATE TABLE HSOFTDKBD.DT_KHOAPHONG
(	KHOAPHONGID NUMBER(2,0) NOT NULL , 
	IDDONVI NUMBER(2,0) NOT NULL, 
        KHOAPHONGTEN NVARCHAR2(100) NOT NULL,
	KHOAPHONGVIETTAT NVARCHAR2(30), 
  CONSTRAINT DT_KHOAPHONG_PK PRIMARY KEY (KHOAPHONGID)
);
SELECT * FROM HSOFTDKBD.DT_KHOAPHONG

alter table  HSOFTDKBD.DT_PHAI
MODIFY PHAITEN NVARCHAR2(4);
------ PHAI
CREATE TABLE HSOFTDKBD.DT_PHAI
(
	PHAIID NUMBER(2,0) NOT NULL ,
	PHAITEN NVARCHAR2(20) NULL,
  CONSTRAINT DT_PHAI_PK PRIMARY KEY (PHAIID)
);
        

------------HOC VIEN
CREATE TABLE HSOFTDKBD.DT_HOCVIEN
(
	HOCVIENID NUMBER(5,0) NOT NULL , 
  IDCHUCDANH NUMBER(2,0) NOT NULL , 
	IDDONVI NUMBER(2,0) NOT NULL , 
	IDKHOAPHONG NUMBER(2,0) NOT NULL , 
        HOCVIENHOTEN NVARCHAR2(100) NOT NULL,
        HOCVIENNAMSINH NVARCHAR2(20) NULL,
	HOCVIENPHAI NVARCHAR2(4) NULL,
        HOCVIENDIENTHOAI NVARCHAR2(20)NULL,
        HOCVIENEMAIL NVARCHAR2(50)  NULL,
        HOCVIENGHICHU NVARCHAR2(500)  NULL,

    CONSTRAINT DT_HOCVIEN_PK PRIMARY KEY (HOCVIENID)
);


-----------NCKH

ALTER TABLE HSOFTDKBD.DT_HOCVIEN
MODIFY HOCVIENPHAI NVARCHAR2(4);

delete from HSOFTDKBD.DT_HOCVIEN
select * from HSOFTDKBD.DT_NCKH
select nckhid,mckhmaso from HSOFTDKBD.DT_NCKH WHERE  hocvienid = 181
update HSOFTDKBD.DT_NCKH set nam = 2020 where nam = 2
DT_NCKH
CREATE TABLE HSOFTDKBD.DT_NCKH
(
	NCKHID NUMBER(5,0) NOT NULL ,
  MCKHMASO NVARCHAR2(8) NULL,
	NAM NUMBER(4,0)  NULL,
	LOAIDETAI NUMBER(1,0)  NULL,
	CHUNHIEM NUMBER(5,0) NOT NULL,
	CONGSU1 NUMBER(5,0) NOT NULL,
	CONGSU2 NUMBER(5,0) NOT NULL,
	CONGSU3 NUMBER(5,0) NOT NULL,
	CONGSU4 NUMBER(5,0) NOT NULL,
	TENDETAI NVARCHAR2(500)  NULL,
	MUCTIEU NVARCHAR2(500)  NULL,
	IDKHOAPHONG NUMBER(3,0)  NULL ,
	LINHVUCNGHIENCUU NUMBER(2,0)  NULL ,
	CAPDETAI NUMBER(1,0)  NULL ,
	THOIGIANDUKIENTU NVARCHAR2(20)  NULL,
	THOIGIANDUKIENDEN NVARCHAR2(20)  NULL,
	KINHPHI NVARCHAR2(50)  NULL,
        TINHTRANGDETAI NUMBER(1,0)  NULL ,
	NGHIEMTHUDECUONG NVARCHAR2(20)  NULL,
	NGHIEMTHUDETAI  NVARCHAR2(20)  NULL,
	GHICHU  NVARCHAR2(500)  NULL,
	NHANVIEN  NVARCHAR2(500)  NULL,
	KETQUANGHIEMTHU  NVARCHAR2(200)  NULL,
  CONSTRAINT DT_NCKH_PK PRIMARY KEY (NCKHID)
);

ALTER TABLE HSOFTDKBD.DT_NCKH ADD MCKHMASO NVARCHAR2(8) NULL;   

------------LOAIDETAI
CREATE TABLE HSOFTDKBD.DT_LOAIDETAI
(
	IDLOAIDETAI NUMBER(2,0) NOT NULL,
	LOAIDETAITEN NVARCHAR2(100) NULL,
    CONSTRAINT DT_IDLDT_PK PRIMARY KEY (IDLOAIDETAI)
};
select * from HSOFTDKBD.DT_LOAIDETAI
delete HSOFTDKBD.DT_LOAIDETAI where idloaidetai = 3

CREATE TABLE HSOFTDKBD.DT_LINHVUCNGHIENCUU
(
	LVNCID NUMBER(2,0) NOT NULL,
	LVNCTEN NVARCHAR2(100) NULL,
     CONSTRAINT DT_LVNC_PK PRIMARY KEY (LVNCID)
);

CREATE TABLE HSOFTDKBD.DT_CAPDETAI
(
	CAPDTID NUMBER(2,0) NOT NULL,
	CAPDTTEN NVARCHAR2(100) NULL,
     CONSTRAINT DT_CAPDT_PK PRIMARY KEY (CAPDTID)
);


CREATE TABLE HSOFTDKBD.DT_TINHTRANGDETAI
(
	TTDTID NUMBER(2,0) NOT NULL,
	TTDTTEN NVARCHAR2(100) NULL,
     CONSTRAINT DT_TTDT_PK PRIMARY KEY (TTDTID)
);

CREATE TABLE HSOFTDKBD.DT_NAMNC
(
	NAMID  NUMBER(2,0) NOT NULL,
	NAMTEN  NUMBER(4,0) NOT NULL,
     CONSTRAINT DT_NAMNC_PK PRIMARY KEY (NAMID)
);
        
SELECT * FROM      HSOFTDKBD.DT_HOCCHUYENKHOA   
CREATE TABLE HSOFTDKBD.DT_HOCCHUYENKHOA
(
	HCKID NUMBER(5,0) NOT NULL,
	HCKNAM NUMBER(4,0) NULL,
	HCKHOCVIENID NUMBER(5,0) NULL,
	KPDAOTAOID NUMBER(2,0) NULL,
	HCKNOIDUNGDAOTAO NVARCHAR2(500) NULL,
	HCKTHOIGIANDAOTAO NUMBER(2,0)  NULL,
	HCKTHOIGIANBATDAU DATE NULL,
	HCKTHOIGIANKETTHUC DATE NULL,
	HCKKINHPHI NVARCHAR2(20) NULL,
	HCKKETQUATB NVARCHAR2(50) NULL,
	HCKKETQUALT NVARCHAR2(50) NULL,
	HCKKETQUATH NVARCHAR2(50) NULL,
	HCKCHUNGNHANID NUMBER(2,0) NULL,
	HCKTINHTRANGDTID NUMBER(2,0) NULL,
	HCKGHICHU NVARCHAR2(500) NULL,
	HCKHOCVIEN NVARCHAR2(500) NULL,
        HCKMASO NVARCHAR2(8) NULL,
        HCKHINHTHUCHOC NVARCHAR2(200) NULL,
        HCKGOIKT NVARCHAR2(200) NULL,
        HCKLOAIKINHPHI NVARCHAR2(100) NULL,
        HCKTONGSOTIET NVARCHAR2(20) NULL,
        HCKCHUNGNHANSO NVARCHAR2(20) NULL,
        HCKSOTIETHOC NVARCHAR2(20) NULL,
        HCKSOTIETNGHI NVARCHAR2(20) NULL,
      CONSTRAINT DT_HCK_PK PRIMARY KEY (HCKID)
   );
   
ALTER TABLE HSOFTDKBD.DT_HOCCHUYENKHOA ADD HCKMASO NVARCHAR2(8) NULL;   
        
 CREATE TABLE HSOFTDKBD.DT_TINHTRANGDAOTAO
   (
	TTDTID NUMBER(2,0) NOT NULL,
	TTDTTEN NVARCHAR2(100) NULL,
      CONSTRAINT DT_TINHTRANGDAOTAO_PK PRIMARY KEY (TTDTID)
   );
  
  SELECT DSLOPDTTLID,  from HSOFTDKBD.DT_DSLOPDTTL WHERE TRANGTHAILOP = 1 ORDER BY NOIDUNGHOC ASC
select * from HSOFTDKBD.DT_DSLOPDTTL   
ALTER TABLE HSOFTDKBD.DT_DSLOPDTTL MODIFY TRANGTHAILOP NUMBER(1,0); 
CREATE TABLE HSOFTDKBD.DT_DSLOPDTTL
(
	DSLOPDTTLID NUMBER(5,0) NOT NULL,
        DTTLMASO NVARCHAR2(8) NULL,
	NAMLOPHOC NUMBER(4,0) NULL,
	NOIDUNGHOC NVARCHAR2(500) NULL,
	BVTOCHUCID NUMBER(2,0) NOT NULL,
	KHOAPHONGID NUMBER(2,0) NOT NULL,
	NGAYBATDAULOPHOC date NULL,
	NGAYKETTHUCLOPHOC date NULL,
        THOIGIANHOC NVARCHAR2(20) NULL,
	THOIGIANHOCLYTHUYET NVARCHAR2(20) NULL,
	THOIGIANHOCTHUCHANH NVARCHAR2(20) NULL,
        LOAICHUNGNHAN NUMBER(2) NULL,
	DIADIEMHOC NVARCHAR2(100) NULL,
	DOITUONGHOC NVARCHAR2(500) NULL,
        IDNGUOIHUONGDAN NUMBER(5,0) NULL, 
	TROGIANGPHOIHOP NVARCHAR2(500) NULL,
	KINHPHI NVARCHAR2(20) NULL,
	CHIGIANGVIEN NVARCHAR2(20) NULL,
	CHINUOCUONG NVARCHAR2(20) NULL,
	CHIKHAC NVARCHAR2(20) NULL,
	LOAIDTID NVARCHAR2(50) NULL,    
        GHICHU NVARCHAR2(500) NULL,
        TRANGTHAILOP NUMBER(1,0) NULL,
     CONSTRAINT DT_DSLOPDTTL_PK PRIMARY KEY (LOPHOCID)
   );
   
   select NOIDUNGHOC ||'  '|| SHKHMASO ||'  '|| NOIDUNGHOC  from HSOFTDKBD.DT_DSLOPSHKH
CREATE TABLE HSOFTDKBD.DT_DSLOPDTTL
(
	DSLOPDTTLID NUMBER(5,0) NOT NULL,
        DTTLMASO NVARCHAR2(8) NULL,
	NAMLOPHOC NUMBER(4,0) NULL,
	NOIDUNGHOC NVARCHAR2(500) NULL,
	BVTOCHUCID NUMBER(2,0) NOT NULL,
	KHOAPHONGID NUMBER(2,0) NOT NULL,
	NGAYBATDAULOPHOC date NULL,
	NGAYKETTHUCLOPHOC date NULL,
        THOIGIANHOC NVARCHAR2(20) NULL,
	THOIGIANHOCLYTHUYET NVARCHAR2(20) NULL,
	THOIGIANHOCTHUCHANH NVARCHAR2(20) NULL,
        LOAICHUNGNHAN NUMBER(2) NULL,
	DIADIEMHOC NVARCHAR2(100) NULL,
	DOITUONGHOC NVARCHAR2(500) NULL,
        IDNGUOIHUONGDAN NUMBER(5,0) NULL, 
	TROGIANGPHOIHOP NVARCHAR2(500) NULL,
	KINHPHI NVARCHAR2(20) NULL,
	CHIGIANGVIEN NVARCHAR2(20) NULL,
	CHINUOCUONG NVARCHAR2(20) NULL,
	CHIKHAC NVARCHAR2(20) NULL,
	LOAIDTID NVARCHAR2(50) NULL,    
        GHICHU NVARCHAR2(500) NULL,
        TRANGTHAILOP NUMBER(1,0) NULL,
     CONSTRAINT DT_DSLOPDTTL_PK PRIMARY KEY (DSLOPDTTLID)
   );
select NOIDUNGHOC ||' - '|| SHKHMASO ||' - '|| NOIDUNGHOC  from HSOFTDKBD.DT_DSLOPSHKH  where SHKHMASO = 'SHKH0001'
select NAMLOPHOC ||'  '|| SHKHMASO ||'  '|| NOIDUNGHOC  from HSOFTDKBD.DT_DSLOPSHKH
select *  from HSOFTDKBD.DT_DSLOPSHKH
CREATE TABLE HSOFTDKBD.DT_DSLOPSHKH
(
	DSLOPSHKHID NUMBER(5,0) NOT NULL,
  SHKHMASO NVARCHAR2(8) NULL,
	NAMLOPHOC NUMBER(4,0) NULL,
	NOIDUNGHOC NVARCHAR2(500) NULL,
	BVTOCHUCID NUMBER(2,0) NOT NULL,
	KHOAPHONGID NUMBER(2,0) NOT NULL,
	NGAYBATDAULOPHOC date NULL,
	NGAYKETTHUCLOPHOC date NULL,
  THOIGIANHOC NVARCHAR2(20) NULL,
	THOIGIANHOCLYTHUYET NVARCHAR2(20) NULL,
	THOIGIANHOCTHUCHANH NVARCHAR2(20) NULL,
  LOAICHUNGNHAN NUMBER(2) NULL,
	DIADIEMHOC NVARCHAR2(100) NULL,
	DOITUONGHOC NVARCHAR2(500) NULL,
        IDNGUOIHUONGDAN NUMBER(5,0) NULL, 
	TROGIANGPHOIHOP NVARCHAR2(500) NULL,
	KINHPHI NVARCHAR2(20) NULL,
	CHIGIANGVIEN NVARCHAR2(20) NULL,
	CHINUOCUONG NVARCHAR2(20) NULL,
	CHIKHAC NVARCHAR2(20) NULL,
	LOAIDTID NVARCHAR2(50) NULL,    
  GHICHU NVARCHAR2(500) NULL,
     CONSTRAINT DT_DSLOPSHKH_PK PRIMARY KEY (DSLOPSHKHID)
   );


   
DROP TABLE HSOFTDKBD.DT_DSLOPDTTL

ALTER TABLE HSOFTDKBD.DT_LOPHOC  
  RENAME TO HSOFTDKBD.DT_DSLOPDTTL;
   
   
ALTER TABLE HSOFTDKBD.DT_LOPHOC  
  MODIFY LOAICHUNGNHAN NUMBER(2);
SELECT LOAICHUNGNHAN FROM  HSOFTDKBD.DT_LOPHOC  
DELETE  HSOFTDKBD.DT_LOPHOC 
  
DELETE HSOFTDKBD.DT_DSHOCVIENDTTL
CREATE TABLE HSOFTDKBD.DT_DSHOCVIENDTTL
(
        HVDTTLID NUMBER(5,0) NOT NULL,
	IDHOCVIEN NUMBER(5,0)  NULL,
	IDLOPHOC NUMBER(5,0) NULL,
	SOTIETHOC NUMBER(5,0) NULL,
	SOTIETNGHI NUMBER(5,0) NULL,
	GOICHUYENGIAOKT NVARCHAR2(500) NULL,
        IDLOAICN NUMBER(2,0)  NULL,
        GHICHU NVARCHAR2(500) NULL,
        UPD date NULL,
    CONSTRAINT DT_DSHOCVIENDTTL_PK PRIMARY KEY (HVDTTLID)
);
DROP TABLE HSOFTDKBD.DT_DSHOCVIENSHKH

SELECT * FROM  HSOFTDKBD.DT_DSHOCVIENDTTL
DELETE HSOFTDKBD.DT_DSHOCVIENSHKH
CREATE TABLE HSOFTDKBD.DT_DSHOCVIENSHKH
(
  HVSHKHID NUMBER(5,0) NOT NULL,
	IDHOCVIEN NUMBER(5,0)  NULL,
	IDLOPHOC NUMBER(5,0) NULL,
	SOTIETHOC NUMBER(2,0) NULL,
	SOTIETNGHI NUMBER(2,0) NULL,
	GOICHUYENGIAOKT NVARCHAR2(1000) NULL,
  IDLOAICN NUMBER(2,0)  NULL,
  GHICHU NVARCHAR2(500) NULL,
  UPD date NULL,
  CONSTRAINT DT_DSHOCVIENSHKH_PK PRIMARY KEY (HVSHKHID)
);




select * from HSOFTDKBD.DT_DSHOCVIENDTTL
ALTER TABLE HSOFTDKBD.DT_DSHOCVIENSHKH modify GOICHUYENGIAOKT NVARCHAR2(500) NULL; 

DROP TABLE HSOFTDKBD.DT_DSHOCVIENDTTL


CREATE TABLE HSOFTDKBD.DT_APDUNGNCKH
(
	ADKHID NUMBER(5,0) NOT NULL,
        ADKHMASO NVARCHAR2(8) NULL,
        ADKHNAM NUMBER(4,0) NULL,
	NOIDUNGAPDUNG NVARCHAR2(500) NULL,
	NGUONKH NVARCHAR2(100) NULL,
        IDKHOAPHONG NUMBER(3,0)  NULL ,
	NGAYBATDAUAPDUNG date NULL,
	NGAYKETTHUCAPDUNG date NULL,
        TIENDOAPDUNG NVARCHAR2(100) NULL,
        ADKHKETQUA NVARCHAR2(100) NULL,
        ADKHGHICHU NVARCHAR2(200) NULL,
        UPD date NULL,
     CONSTRAINT DT_APDUNGNCKH_PK PRIMARY KEY (ADKHID)
);

ALTER TABLE HSOFTDKBD.DT_CAPCHUNGNHAN MODIFY CCNMASO NVARCHAR2(12);   

update HSOFTDKBD.DT_CAPCHUNGNHAN set SOCHUNGNHAN= '01/2021 - C61.01' 
CREATE TABLE HSOFTDKBD.DT_CAPCHUNGNHAN
(
	CCNID NUMBER(5,0) NOT NULL,
        CCNNAM NUMBER(4,0) NOT NULL,
        CCNMASO NVARCHAR2(8) NULL, --MASOLOP
        CCNSO NUMBER(4,0) NOT NULL,
        SOCHUNGNHAN NVARCHAR2(30) NULL,  --     CCNSO/ CCNNAM - C61.01                  ----SO LAP LAI THEO NAM  
        IDHOCVIEN NUMBER(5,0) NULL,
	HOTENHV NVARCHAR2(100) NULL,
	PHAI NVARCHAR2(10) NULL,
        NGAYSINH NVARCHAR2(15)  NULL ,
	CHUCDANH NVARCHAR2(100)  NULL ,
	DONVICT NVARCHAR2(200)  NULL ,
        IDLOP NUMBER(5,0) NULL,
        TENLOP NVARCHAR2(500) NULL,
        SOTIETHOC NUMBER(3,0) NULL,
        TUNGAY date NULL,
	DENNGAY date NULL,
        PHUTRACH NUMBER(5,0) NULL,
        GHICHU NVARCHAR2(500) NULL
        UPD date NULL,
     CONSTRAINT DT_CAPCHUNGNHAN_PK PRIMARY KEY (CCNID)
);

select SOCHUNGNHAN from HSOFTDKBD.DT_CAPCHUNGNHAN where IDLOP = 1 and IDHOCVIEN = 1 and CCNMASO ='0123'

CREATE TABLE HSOFTDKBD.DT_CHUYENGIAOKYTHUATLL
(
	CGKTID NUMBER(5,0) NOT NULL,
        CGKTNAM NUMBER(4,0) NOT NULL,
        CGKTMASO NVARCHAR2(8) NULL,  -- CGKT + 000+CGKTID
        CGKTTENGOI NVARCHAR2(500) NULL,
        IDDVNHANCGKTLL NUMBER(3,0) NULL,
        CGKTBATDAU DATE NULL,
        CGKTKETTHUC DATE NULL,
        IDKHOAPHONGCGKT NUMBER(3,0) NULL,
        IDCBDMCGKT NUMBER(5,0) NULL,
 	GHICHU NVARCHAR2(500) NULL,
        UPD date NULL,
     CONSTRAINT DT_CHUYENGIAOKYTHUATLL_PK PRIMARY KEY (CGKTID)
);

ALTER TABLE HSOFTDKBD.DT_CHUYENGIAOKYTHUATLL add IDKHOAPHONGCGKT NUMBER(3,0) NULL;   


CREATE TABLE HSOFTDKBD.DT_CHUYENGIAOKYTHUATCT
(
	CGKTCTID NUMBER(5,0) NOT NULL,
        CGKTID NUMBER(5,0) NULL,   
        NGAYCGKT DATE NULL,
        CGKTQD NVARCHAR2(20) NULL,
        IDNHANVIENCGKT NUMBER(5,0) NULL,
        NHANVIENHOTROCGKT NVARCHAR2(500) NULL,
        CGKTNOIDUNG NVARCHAR2(500) NULL,
        IDDVNHANCGKT NUMBER(3,0) NULL,
        NHANVIENNHANHOTROCGKT NVARCHAR2(500) NULL,
        CGKTCTBATDAU DATE NULL,
        CGKTCTKETTHUC DATE NULL,
	GHICHU NVARCHAR2(500) NULL,
        UPD date NULL,
     CONSTRAINT DT_CHUYENGIAOKYTHUATCT_PK PRIMARY KEY (CGKTCTID)
);


DELETE  HSOFTDKBD.DT_CHUYENGIAOKYTHUATCT
DROP TABLE HSOFTDKBD.DT_CHUYENGIAOKYTHUATCT

insert into HSOFTDKBD.DT_CHAMCONG  (CCHCKID, MMYY, IDHOCVIEN, IDHCK, IDKHOAPHONG) values (1,'0620',1,1,2)", MMYY, IDHOCVIEN, IDHCK, IDKHOAPHONG)
CREATE TABLE HSOFTDKBD.DT_CHAMCONG
(
	CCHCKID NUMBER(5,0) NOT NULL,
        MMYY NVARCHAR2(4) NOT NULL,
        IDHOCVIEN NUMBER(5,0) NOT NULL,
        IDHCK NUMBER(5,0) NOT NULL,
        IDKHOAPHONG NUMBER(3,0) NOT NULL,
        HCKTHOIGIANBATDAU DATE NULL,
	HCKTHOIGIANKETTHUC DATE NULL,
        N1 NVARCHAR2(10) NULL,
        N2 NVARCHAR2(10) NULL,
        N3 NVARCHAR2(10) NULL,
        N4 NVARCHAR2(10) NULL,
        N5 NVARCHAR2(10) NULL,
        N6 NVARCHAR2(10) NULL,
        N7 NVARCHAR2(10) NULL,
        N8 NVARCHAR2(10) NULL,
        N9 NVARCHAR2(10) NULL,
        N10 NVARCHAR2(10) NULL,
        N11 NVARCHAR2(10) NULL,
        N12 NVARCHAR2(10) NULL,
        N13 NVARCHAR2(10) NULL,
        N14 NVARCHAR2(10) NULL,
        N15 NVARCHAR2(10) NULL,
        N16 NVARCHAR2(10) NULL,
        N17 NVARCHAR2(10) NULL,
        N18 NVARCHAR2(10) NULL,
        N19 NVARCHAR2(10) NULL,
        N20 NVARCHAR2(10) NULL,
        N21 NVARCHAR2(10) NULL,
        N22 NVARCHAR2(10) NULL,
        N23 NVARCHAR2(10) NULL,
        N24 NVARCHAR2(10) NULL,
        N25 NVARCHAR2(10) NULL,
        N26 NVARCHAR2(10) NULL,
        N27 NVARCHAR2(10) NULL,
        N28 NVARCHAR2(10) NULL,
        N29 NVARCHAR2(10) NULL,
        N30 NVARCHAR2(10) NULL,
        N31 NVARCHAR2(10) NULL,
        GHICHU NVARCHAR2(200) NULL,
        TINHTRANG NUMBER(1,0) NULL,
        UPD date NULL,
        
     CONSTRAINT DT_CHAMCONG_PK PRIMARY KEY (CCHCKID)
);
select * from HSOFTDKBD.DT_CHAMCONG where idhocvien = 178 and idhck = 47 and idkhoaphong = 10
delete HSOFTDKBD.DT_CHAMCONG where idhocvien = 178 and idhck = 47 and idkhoaphong = 10
delete HSOFTDKBD.DT_CHAMCONGDTTL 
CREATE TABLE HSOFTDKBD.DT_CHAMCONGDTTL
(
	CCDTTLID NUMBER(5,0) NOT NULL,
        MMYY NVARCHAR2(4) NOT NULL,
        IDHOCVIEN NUMBER(5,0) NOT NULL,
        MALOP NUMBER(5,0) NOT NULL,
        IDKHOAPHONG NUMBER(3,0) NOT NULL,
        HCKTHOIGIANBATDAU DATE NULL,
	HCKTHOIGIANKETTHUC DATE NULL,
        N1 NVARCHAR2(10) NULL,
        N2 NVARCHAR2(10) NULL,
        N3 NVARCHAR2(10) NULL,
        N4 NVARCHAR2(10) NULL,
        N5 NVARCHAR2(10) NULL,
        N6 NVARCHAR2(10) NULL,
        N7 NVARCHAR2(10) NULL,
        N8 NVARCHAR2(10) NULL,
        N9 NVARCHAR2(10) NULL,
        N10 NVARCHAR2(10) NULL,
        N11 NVARCHAR2(10) NULL,
        N12 NVARCHAR2(10) NULL,
        N13 NVARCHAR2(10) NULL,
        N14 NVARCHAR2(10) NULL,
        N15 NVARCHAR2(10) NULL,
        N16 NVARCHAR2(10) NULL,
        N17 NVARCHAR2(10) NULL,
        N18 NVARCHAR2(10) NULL,
        N19 NVARCHAR2(10) NULL,
        N20 NVARCHAR2(10) NULL,
        N21 NVARCHAR2(10) NULL,
        N22 NVARCHAR2(10) NULL,
        N23 NVARCHAR2(10) NULL,
        N24 NVARCHAR2(10) NULL,
        N25 NVARCHAR2(10) NULL,
        N26 NVARCHAR2(10) NULL,
        N27 NVARCHAR2(10) NULL,
        N28 NVARCHAR2(10) NULL,
        N29 NVARCHAR2(10) NULL,
        N30 NVARCHAR2(10) NULL,
        N31 NVARCHAR2(10) NULL,
        GHICHU NVARCHAR2(500) NULL,
        TINHTRANG NUMBER(1,0) NULL,
        UPD date NULL,
        
     CONSTRAINT DT_CHAMCONGDTTL_PK PRIMARY KEY (CCDTTLID)
);

DROP TABLE HSOFTDKBD.DT_CHAMCONGDTTLSHKH




ALTER TABLE HSOFTDKBD.DT_CHAMCONG add TINHTRANG NUMBER(1,0) NULL;   

select * from HSOFTDKBD.DT_CHAMCONG
select * from HSOFTDKBD.DT_DMCHAMCONG
CREATE TABLE HSOFTDKBD.DT_DMCHAMCONG
(
        DMCDID NUMBER(5,0) NOT NULL,
        DMCDVIETTAT NVARCHAR2(10) NULL,
        DMCDTEN NVARCHAR2(100) NULL,
        SONGAYCONG NUMBER(2,0) NULL,
        SOTIETHOC NUMBER(2,0) NULL,
        GHICHU NVARCHAR2(200) NULL,
        UPD date NULL,
        CONSTRAINT DT_DMCHAMCONG_PK PRIMARY KEY (DMCDID)
);
CREATE TABLE HSOFTDKBD.DT_MOCHAMCONG
(
	MOCCID NUMBER(5,0) NOT NULL,
        HCKTHOIGIANBATDAU DATE NULL,
	HCKTHOIGIANKETTHUC DATE NULL,
        CONSTRAINT DT_MOCHAMCONG_PK PRIMARY KEY (MOCCID)
);
INSERT INTO HSOFTDKBD.DT_MOCHAMCONG (MOCCID) VALUES (1);
INSERT INTO HSOFTDKBD.DT_DMCHAMCONG (DMCDID, DMCDTEN,DMCDVIETTAT,SONGAYCONG,SOTIETHOC,GHICHU) VALUES (2,'V?ng m?t','V',0,0,'V?ng không lý do')

s
select * from HSOFTDKBD.DT_DMCHAMCONG
DELETE HSOFTDKBD.DT_CHAMCONG
select COUNT(*) from HSOFTDKBD.DT_CHAMCONG WHERE IDHCK = 6  AND MMYY = '0620'


select COUNT(NCKHID)+1 from HSOFTDKBD.DT_NCKH
select MAX(NCKHID) from HSOFTDKBD.DT_NCKH

DELETE HSOFTDKBD.DT_CHAMCONGDTTL where IDHOCVIEN = 1 and MALOP = 1
SELECT * FROM HSOFTDKBD.DT_CHAMCONGDTTL
select COUNT(*) from HSOFTDKBD.DT_CHAMCONG WHERE IDHCK = 1  AND MMYY = '0620' 
UPDATE HSOFTDKBD.DT_CHAMCONGDTTL SET  TINHTRANG = 0  where MALOP = 1 and IDHOCVIEN = 13
select COUNT(*) from HSOFTDKBD.DT_CHAMCONGDTTL WHERE MMYY = '0720'  AND and MALOP = 1 AND IDHOCVIEN = 13
SELECT DTTLMASO as MA_LOP,NAMLOPHOC as NAM_HOC, NOIDUNGHOC as NOI_DUNG_HOC,(select dvct.DONVITEN from HSOFTDKBD.DT_BENHVIEN dvct where dvct.DONVIID = lh.BVTOCHUCID) as DV_MO_LOP, (SELECT KHOAPHONGTEN FROM  HSOFTDKBD.DT_KHOAPHONG KP WHERE  KP.KHOAPHONGID = LH.KHOAPHONGID) as KHOA_PHONG_MO_LOP, HV.HOCVIENHOTEN as GV_HUONG_DAN, (select cd.ChucDanhTen from HSOFTDKBD.DT_CHUCDANH cd where cd.CHUCDANHID = hv.IDCHUCDANH) as CHUC_DANH, (select dvct.DONVITEN from HSOFTDKBD.DT_BENHVIEN dvct where dvct.DONVIID = HV.IDDONVI) as DON_VI_CONG_TAC,(select kp.KHOAPHONGTEN from HSOFTDKBD.DT_KHOAPHONG kp where kp.KHOAPHONGID = HV.HOCVIENID) as KHOA_PHONG_CONG_TAC, TROGIANGPHOIHOP AS TRO_GIANG_PHOI_HOP, DOITUONGHOC as DOI_TUONG_HOC,NGAYBATDAULOPHOC as NGAY_BAT_DAU,NGAYKETTHUCLOPHOC as NGAY_KET_THUC,THOIGIANHOC as THOI_GIAN_HOC,THOIGIANHOCLYTHUYET as THOI_GIAN_LT ,THOIGIANHOCTHUCHANH as THOI_GIAN_TH,(SELECT CNDTTEN FROM hsoftdkbd.DT_CNDAOTAO  LCNDT WHERE LCNDT.CNDTID = LH.LOAICHUNGNHAN) AS LOAI_CHUNG_NHAN, DIADIEMHOC as DIA_DIEM_HOC,KINHPHI as KINH_PHI,CHIGIANGVIEN as CHI_GV,CHINUOCUONG as CHI_NUOC_UONG,CHIKHAC as CHI_KHAC,GHICHU as GHI_CHU, LH.KHOAPHONGID FROM HSOFTDKBD.DT_DSLOPDTTL lh LEFT JOIN HSOFTDKBD.DT_HOCVIEN HV ON HV.HOCVIENID = LH.IDNGUOIHUONGDAN
insert into HSOFTDKBD.DT_CHAMCONGDTTL  (CCDTTLID, MMYY, IDHOCVIEN, MALOP, IDKHOAPHONG,HCKTHOIGIANBATDAU,HCKTHOIGIANKETTHUC, TINHTRANG) values (1,'0120',1,1,10,to_date('07/01/2020','MM/dd/yyyy'),to_date('12/31/2020','MM/dd/yyyy'),1)
insert into HSOFTDKBD.DT_CHAMCONGDTTL  (CCDTTLID, MMYY, IDHOCVIEN, MALOP, IDKHOAPHONG,HCKTHOIGIANBATDAU,HCKTHOIGIANKETTHUC, TINHTRANG) values ((select COUNT(CCDTTLID) from HSOFTDKBD.DT_CHAMCONGDTTL) ,'0120',1,1,10,to_date('07/01/2020','dd/MM/yyyy'),to_date('12/31/2020','dd/MM/yyyy'),1)

SELECT * FROM  HSOFTDKBD.DT_CHAMCONGDTTL
insert into HSOFTDKBD.DT_CHAMCONGDTTL  (CCDTTLID, MMYY, IDHOCVIEN, MALOP, IDKHOAPHONG,HCKTHOIGIANBATDAU,HCKTHOIGIANKETTHUC, TINHTRANG) values (1,'0720',13,1,10,to_date('07/01/2020 12:00:00 AM','MM/dd/yyyy'),to_date('12/31/2020 12:00:00 AM','MM/dd/yyyy'),1)

DELETE HSOFTDKBD.DT_CHAMCONGDTTL

insert into HSOFTDKBD.DT_CHAMCONGDTTL  (CCDTTLID, MMYY, IDHOCVIEN, MALOP, IDKHOAPHONG,HCKTHOIGIANBATDAU,HCKTHOIGIANKETTHUC, TINHTRANG) values ((select max(CCDTTLID) +1  from HSOFTDKBD.DT_CHAMCONGDTTL) ,'01100',13,1,10,to_date('07/01/2020','MM/dd/yyyy'),to_date('12/31/2020','MM/dd/yyyy'),1)


UPDATE HSOFTDKBD.DT_CHAMCONGDTTL SET  IDKHOAPHONG = 10 , HCKTHOIGIANBATDAU = to_date('07/01/2020','dd/MM/yyyy'),HCKTHOIGIANKETTHUC = to_date('12/31/2020','dd/MM/yyyy'), TINHTRANG = 1 WHERE MALOP = 1 AND MMYY = '0720' AND IDHOCVIEN = 1
SELECT MMYY AS MMYY,DTTL.DTTLMASO AS MA_LOP,HV.HOCVIENHOTEN AS HOC_VIEN, (SELECT KP.KHOAPHONGTEN FROM HSOFTDKBD.DT_KHOAPHONG KP WHERE KP.KHOAPHONGID = CC.IDKHOAPHONG) AS KHOA_DAO_TAO, DTTL.HCKNOIDUNGDAOTAO AS TEN_LOP,N1,N2,N3,N4,N5,N6,N7,N8,N9,N10,N11,N12,N13,N14,N15,N16,N17,N18,N19,N20,N21,N22,N23,N24,N25,N26,N27,N28,N29,N30,N31, CC.GHICHU FROM HSOFTDKBD.DT_CHAMCONGDTTL CC INNER JOIN HSOFTDKBD.DT_DSLOPDTTL DTTL ON DTTL.DSLOPDTTLID = CC.MALOP INNER JOIN HSOFTDKBD.DT_HOCVIEN HV ON HV.HOCVIENID = CC.IDHOCVIEN  WHERE CC.TINHTRANG > 0 AND MMYY ='0720'
select * from HSOFTDKBD.DT_DSLOPDTTL



SELECT DTTLMASO,
NAMLOPHOC,
NOIDUNGHOC,
(select dvct.DONVITEN from HSOFTDKBD.DT_BENHVIEN dvct where dvct.DONVIID = lh.BVTOCHUCID) as DV_MO_LOP,
(SELECT KHOAPHONGTEN FROM  HSOFTDKBD.DT_KHOAPHONG KP WHERE  KP.KHOAPHONGID = LH.KHOAPHONGID) as KHOA_PHONG_MO_LOP,
HV.HOCVIENHOTEN as GV_HUONG_DAN,
(select cd.ChucDanhTen from HSOFTDKBD.DT_CHUCDANH cd where cd.CHUCDANHID = hv.IDCHUCDANH) as CHUC_DANH,
(select dvct.DONVITEN from HSOFTDKBD.DT_BENHVIEN dvct where dvct.DONVIID = HV.IDDONVI) as DON_VI_CONG_TAC,
(select kp.KHOAPHONGTEN from HSOFTDKBD.DT_KHOAPHONG kp where kp.KHOAPHONGID = HV.HOCVIENID) as KHOA_PHONG_CONG_TAC,
TROGIANGPHOIHOP AS TRO_GIANG_PHOI_HOP,
DOITUONGHOC as DOI_TUONG_HOC,
NGAYBATDAULOPHOC as NGAY_BAT_DAU,
NGAYKETTHUCLOPHOC as NGAY_KET_THUC,
THOIGIANHOC as THOI_GIAN_HOC,
THOIGIANHOCLYTHUYET as THOI_GIAN_LT,
THOIGIANHOCTHUCHANH as THOI_GIAN_TH,
(SELECT CNDTTEN FROM hsoftdkbd.DT_CNDAOTAO  LCNDT WHERE LCNDT.CNDTID = LH.LOAICHUNGNHAN) AS LOAI_CHUNG_NHAN,
DIADIEMHOC as DIA_DIEM_HOC,
KINHPHI as KINH_PHI,
CHIGIANGVIEN as CHI_GV,CHINUOCUONG as CHI_NUOC_UONG,
CHIKHAC as CHI_KHAC,
GHICHU as GHI_CHU,
LH.KHOAPHONGID, 
lh.TRANGTHAILOP,
LH.DSLOPDTTLID,DSLOPDTTLID
LH.NAMLOPHOC,
LH.BVTOCHUCID,
LH.IDNGUOIHUONGDAN,
LH.LOAIDTID


SELECT COUNT(IDLOPHOC) FROM HSOFTDKBD.DT_DSHOCVIENDTTL where IDLOPHOC =3
select *  from HSOFTDKBD.DT_DSHOCVIENDTTL

select * from HSOFTDKBD.DT_DSHOCVIENDTTL

select *  from hsoftdkbd.DT_CNDAOTAO

select dt.IDHOCVIEN  as MA_NVHV,hv.HOCVIENHOTEN as HO_TEN_HV,p.PHAITEN as PHAI,hv.HOCVIENNAMSINH as NGAY_SINH,cd.CHUCDANHTEN as CHUC_DANH ,dv.DONVITEN as DON_VI_CONG_TAC,kp.KHOAPHONGTEN as KHOA_PHONG, lh.DTTLMASO as MA_LOP,lh.NOIDUNGHOC as TEN_LOP, dt.SOTIETHOC as SO_TIET_HOC, dt.SOTIETNGHI as SO_TIET_NGHI,dt.GOICHUYENGIAOKT as GOI_KT, cndt.CNDTTEN AS LOAI_CHUNG_NHAN,dt.GHICHU as GHI_CHU,DT.IDLOPHOC,lh.loaichungnhan,lh.ngaybatdaulophoc,LH.ngayketthuclophoc,LH.khoaphongid,DT.IDLOAICN from HSOFTDKBD.DT_DSHOCVIENDTTL dt inner join HSOFTDKBD.DT_HOCVIEN hv on dt.IDHOCVIEN = hv.HOCVIENID inner join HSOFTDKBD.DT_DSLOPDTTL lh on lh.DSLOPDTTLID = dt.IDLOPHOC left join HSOFTDKBD.DT_PHAI p on p.PHAITEN = hv.HOCVIENPHAI left join HSOFTDKBD.DT_CHUCDANH cd on cd.CHUCDANHID = hv.IDCHUCDANH left join HSOFTDKBD.DT_BENHVIEN dv on dv.DONVIID = hv.IDDONVI left join HSOFTDKBD.DT_KHOAPHONG kp on kp.KHOAPHONGID = hv.IDKHOAPHONG left join hsoftdkbd.DT_CNDAOTAO  cndt on cndt.CNDTID = dt.IDLOAICN 
WHERE lh.DSLOPDTTLID = 3
ORDER BY dt.IDHOCVIEN ASC

CREATE TABLE HSOFTDKBD.CDT_CHECKBHYT
  (ID NVARCHAR2(20) NOT NULL, 
	MABN NVARCHAR2(8)  NULL,   
	HOTEN NVARCHAR2(50)  NULL,
  NAMSINH NVARCHAR2(10)  NULL,
  PHAI NVARCHAR2(1)  NULL,
  NGVAO NVARCHAR2(20) NULL,
  NGRA NVARCHAR2(20) NULL,
  MATHE NVARCHAR2(20) NULL,
  KCBBD NVARCHAR2(5) NULL,
  TUNGAY NVARCHAR2(10) NULL,
  DENNGAY NVARCHAR2(10) NULL,
  MAKQ_TC NVARCHAR2(6) NULL,
  GHICHU_TC NVARCHAR2(500) NULL,
  HOTEN_TC NVARCHAR2(50) NULL,
  NAMSINH_TC NVARCHAR2(10) NULL,
  GIOITINH_TC NVARCHAR2(6) NULL,
  MATHE_TC NVARCHAR2(20) NULL,
  KCBBD_TC NVARCHAR2(5) NULL,
  TUNGAY_TC NVARCHAR2(10) NULL,
  DENNGAY_TC NVARCHAR2(10) NULL,
  CHECK_OK NUMBER(1,0) NULL,
  THANG NVARCHAR2(4) NULL,
  HOTENKHONGDAU NVARCHAR2(50) NULL,
  HOTENKHONGDAU_TC NVARCHAR2(50) NULL;
  CONSTRAINT CDT_CHECKBHYT_PK PRIMARY KEY (ID)
);

CREATE TABLE HSOFTDKBD.CDT_CHECKNGAYGIUONG
  (ID NVARCHAR2(20) NOT NULL,
  CONSTRAINT CDT_CHECKNGAYGIUONG_PK PRIMARY KEY (ID)
  );
  
CREATE TABLE HSOFTDKBD.CDT_MAGIUONG
  (ID NVARCHAR2(2000) NOT NULL,
  CONSTRAINT CDT_MAGIUONG_PK PRIMARY KEY (ID)
  );


ALTER TABLE HSOFTDKBD.CDT_CHECKBHYT ADD HOTENKHONGDAU_TC NVARCHAR2(50) NULL;
ALTER TABLE HSOFTDKBD.CDT_CHECKBHYT ADD LOI NVARCHAR2(50) NULL;
alter table  HSOFTDKBD.CDT_CHECKBHYT
MODIFY LOI NVARCHAR2(100);


DROP TABLE HSOFTDKBD.CDT_MAGIUONG


 
( select LL.ID,BN.MABN,BN.HOTEN, BN.NAMSINH,BN.PHAI,TO_CHAR(LL.NGAYVAO,'DD_MM_YYYY_HH24:MI'),TO_CHAR(LL.NGAYRA,'DD_MM_YYYY_HH24:MI'),SUBSTR(LL.SOTHE,1,15),SUBSTR(LL.SOTHE,16,20),TO_CHAR(LL.TUNGAY,'DD/MM/YYYY'), TO_CHAR(LL.TUNGAY,'DD/MM/YYYY')
from hsoftdkbd0922.v_m38ll LL 
INNER JOIN hsoftdkbd.BTDBN BN ON BN.MABN = LL.MABN
where LL.ID NOT IN (SELECT ID FROM hsoftdkbd.CDT_CHECKBHYT))

SELECT THANG, ID, MABN,   HOTEN ,NAMSINH ,PHAI ,NGVAO ,NGRA ,MATHE ,KCBBD ,TUNGAY ,DENNGAY ,MAKQ_TC ,GHICHU_TC ,HOTEN_TC ,NAMSINH_TC ,GIOITINH_TC,MATHE_TC ,KCBBD_TC ,TUNGAY_TC ,DENNGAY_TC ,CHECK_OK 

FROM HSOFTDKBD.CDT_CHECKBHYT


DELETE FROM HSOFTDKBD.CDT_CHECKBHYT where  id =209031608492965509
select * from HSOFTDKBD.CDT_MAGIUONG where mabn =22136736  NOT NULL = '22934094' and id in (209061042123590233,209061042049137660,209061041240445262,209061041325206938,209061039330618506)

UPDATE HSOFTDKBD.CDT_CHECKBHYT SET HOTENKHONGDAU_TC = HOTENKHONGDAU

select mabn, HOTENKHONGDAU from HSOFTDKBD.CDT_CHECKBHYT
select count(*) from HSOFTDKBD.CDT_CHECKBHYT where makq_tc ='401'
select * FROM hsoftdkbd.CDT_CHECKNGAYGIUONG 


create user CDT identified by HSOFTDKBD;
GRANT CONNECT TO CDT;
GRANT UNLIMITED TABLESPACE TO CDT;

SELECT * FROM DBA_ROLES;
GRANT CREATE TABLE TO CDT;




SELECT LOI, Thang,TENKP,MABN, NGVAO ,NGRA ,HOTEN, NAMSINH ,PHAI ,GIOITINH_TC, MATHE ,  KCBBD ,KCBBD_TC , TUNGAY ,TUNGAY_TC , DENNGAY ,DENNGAY_TC , MAKQ_TC ,GHICHU_TC,  ID, CHECK_OK  FROM HSOFTDKBD.CDT_CHECKBHYT 
                WHERE  THANG = '1122' AND TENKP != 'Khoa S? Sinh' AND CHECK_OK = '0' AND PHAI != GIOITINH_TC
                
                (SUBSTR(MATHE,0,2) NOT IN ('QN','CA') AND THANG ='1122' AND TENKP != 'Khoa S? Sinh' AND CHECK_OK = '0' AND KCBBD != KCBBD_TC)
                ORDER BY LOI ASC


--------cap nhat danh muc giuong ------------------------------------
insert into hsoftdkbd.CDT_MAGIUONG (id) values ('140402,140401,140400,140399,140398,140113,140112,140111,140110,140109,140108,140106,140105,140104,140103,140102,140101,140098,139336,139335,139334,139333,139244,139243,139242,139241,139240,139072,139058,139337,139240,139241,139242,139243,139244,139072,139058,128816,128814,128813,128812,128811,128810,128809,128807,128806,128805, 124277,94487, 2715,2716,2717,2718,2719,2720,2721,2722,2723,2724,2725,2726,2727,2728,2729,2730,2731,2732,2733,2734,2735,2736,2737,2738,2739,2740,2741,2742,2743,2744,2745,2746,2747,2748,2749,2750,2751,2752,2753,2754,2755,2756,2757,2758,2759,2760,2761,2762,2763,2764,2765,2766,2767,2768,2769,2770,2771,2772,2773,2774,2775,2776,2777,2778,2779,2780,2781,2782,2783,2784,2785,2786,2787,2788,2789,2790,2791,2792,2793,2794,106489,106490,106491,106492,106494,106495,106496,106497,106498,106499,106503,106504,106505,106506,106507,106508,106509,106510,106511,106674,106675,106676,106677,106680,106681,106682,106683,106684,106685,106686,106687,106688,106689,106690,106691,112153')


